---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  # Quick check so we don't waste minutes if there's a Flake8 error
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        ckan-version: ['2.10']
        ckan-type: ['vanilla', 'custom']
        experimental: [false]
        include:
          - ckan-version: '2.11'
            ckan-type: 'vanilla'
            experimental: true
          - ckan-version: '2.11'
            ckan-type: 'custom'
            experimental: false
          - ckan-version: 'master'
            experimental: true  # master is unstable, good to know if we are compatible or not

    name: ${{ matrix.experimental && '**Fail_Ignored** ' || '' }} Run tests on CKAN ${{ matrix.ckan-version }} ${{ matrix.ckan-type }}
    runs-on: ubuntu-latest
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}
      CKAN_TYPE: ${{ matrix.ckan-type }}

    steps:
      - uses: actions/checkout@v7
        continue-on-error: ${{ matrix.experimental }}
        timeout-minutes: 2

      - name: Install Ahoy and dependencies
        continue-on-error: ${{ matrix.experimental }}
        run: |
          sudo wget https://github.com/ahoy-cli/ahoy/releases/download/v2.5.0/ahoy-bin-linux-amd64 -O /usr/local/bin/ahoy \
            && sudo chown $USER /usr/local/bin/ahoy \
            && chmod +x /usr/local/bin/ahoy
          sudo wget https://github.com/pygmystack/pygmy/releases/download/v0.14.0/pygmy_0.14.0_linux_amd64.tar.gz -O - | tar xvzf - -C /tmp/ \
            && sudo mv /tmp/pygmy /usr/local/bin/pygmy

      - name: Build
        run: bin/build.sh
        timeout-minutes: 15
        continue-on-error: ${{ matrix.experimental }}

      - name: Lint
        run: ahoy lint
        timeout-minutes: 10
        continue-on-error: ${{ matrix.experimental }}

      - name: Unit test
        run: ahoy test-unit
        timeout-minutes: 10
        continue-on-error: ${{ matrix.experimental }}

      - name: Scenario test
        run: |
          ahoy install-site
          ahoy test-bdd
        timeout-minutes: 30
        continue-on-error: ${{ matrix.experimental }}

      - name: Retrieve logs
        if: always()
        run: ahoy logs
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}

      - name: Retrieve results
        if: always()
        run: bin/process-artifacts.sh
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}

      - name: Test Summary
        uses: test-summary/action@v2
        continue-on-error: ${{ matrix.experimental }}
        with:
          paths: "/tmp/artifacts/junit/*.xml"
        if: always()

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CKAN ${{ matrix.ckan-version }} ${{ matrix.ckan-type }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}
