---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  # Quick check so we don't waste minutes if there's a Flake8 error
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        ckan-version: ['2.11']
        ckan-type: ['vanilla', 'custom']
        experimental: [false]
        include:
          - ckan-version: '2.12'
            ckan-type: 'vanilla'
            experimental: false
          - ckan-version: 'master'
            experimental: true  # master is unstable, good to know if we are compatible or not

    name: ${{ matrix.experimental && '**Fail_Ignored** ' || '' }} Run tests on CKAN ${{ matrix.ckan-version }} ${{ matrix.ckan-type }}
    runs-on: ubuntu-latest
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}
      CKAN_TYPE: ${{ matrix.ckan-type }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        timeout-minutes: 2
        continue-on-error: ${{ matrix.experimental }}

      - name: Build
        run: ./build.sh
        timeout-minutes: 15
        continue-on-error: ${{ matrix.experimental }}

      - name: Lint
        run: ./build.sh lint
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}

      - name: Unit test
        run: ./build.sh test_unit
        timeout-minutes: 10
        continue-on-error: ${{ matrix.experimental }}

      - name: Scenario test
        run: ./build.sh test_bdd
        timeout-minutes: 30
        continue-on-error: ${{ matrix.experimental }}

      - name: Retrieve logs
        if: always()
        run: ./build.sh logs
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}

      - name: Retrieve results
        if: always()
        run: ./build.sh process_artifacts
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}

      - name: Test Summary
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5  # v2.6
        continue-on-error: ${{ matrix.experimental }}
        with:
          paths: "/tmp/artifacts/junit/*.xml"
        if: always()

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: CKAN ${{ matrix.ckan-version }} ${{ matrix.ckan-type }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}
