---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        ckan-version: [2.9, 2.9-py2, 2.8]

    name: Continuous Integration build on CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container: integratedexperts/ci-builder
    timeout-minutes: 360
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}

    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2

      - name: Build
        run: .circleci/build.sh
        timeout-minutes: 15

      - name: Pip list
        run: ahoy pip-list
        timeout-minutes: 15

      - name: Test
        run: .circleci/test.sh
        timeout-minutes: 25

      - name: Retrieve screenshots
        if: failure()
        run: .circleci/process-artifacts.sh
        timeout-minutes: 1

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: CKAN ${{ matrix.ckan-version }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
