---
#based on https://raw.githubusercontent.com/ckan/ckanext-scheming/master/.github/workflows/test.yml
# alternative https://github.com/ckan/ckan/blob/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/.github/workflows/test.yml
name: Tests
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ckan-version: [2.8.8-qgov.4, 2.9.3]

    name: Continuous Integration build on CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container: integratedexperts/ci-builder
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}

    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2

      - name: Build
        run: .circleci/build.sh
        timeout-minutes: 10

      - name: Test
        run: .circleci/test.sh
        timeout-minutes: 15

      - name: Retrieve screenshots
        if: failure()
        run: .circleci/process-artifacts.sh
        timeout-minutes: 1

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
